[package]
name = "j-cli-gui"
version = "0.1.0"
edition = "2024"
rust-version = "1.93.1"

[lib]
name = "j_cli_gui_lib"
crate-type = ["lib", "cdylib", "staticlib"]
path = "src/lib.rs"

[[bin]]
name = "j-cli-gui"
path = "src/main.rs"

[dependencies]
j-cli = { path = "../.." }
tauri = { version = "2", features = ["macos-private-api", "tray-icon"] }
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[build-dependencies]
tauri-build = { version = "2", features = [] }
